gaming_data:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: gamingdata-487900
      keyfile: "{{ env_var('DBT_GOOGLE_CREDENTIALS') }}"
      dataset: gaming_data
      threads: 4
      location: US
